### ISSUE TITLE
Purification of Cv2025 (PE) and preparation of crude-cell extract (CCE)

### ISSUE THREAD

**Issue by LauraGrabowski** [LauraGrabowski/student-project#12]

**Comment by AnnekeStrumpel** [comment]
Aufreinigung aus 14.45 g Zellpellet erfolgreich, Zielenzymkonzentration 33 %, es wurden ~750 mg Lyophilisat mit aufgereinigter Cv2025 gewonnen. Proteingehalt im Lyophilisat ~29%

CCE: zweites Pellet (18.7g) wurde in 200 mL 50 mM HEPES pH 7.5 0.2 mM PLP gelöst (Konzentration CCE: 9.06 mg/mL), aufgeschlossen und lyophilisiert

**Comment by AnnekeStrumpel** [comment]
Aufgabe wir weiter in #11
