### ISSUE TITLE
Aufreinigung **ApPDC E469Q** + Herstellung Rohzellextrakt

### ISSUE THREAD

**Issue by LauraGrabowski** [LauraGrabowski/student-project#4]
- Aufreinigung 1 am 07.09.21
- 110 mL Entsalzungsfraktion mit ca. 1 mg/mL Protein in Tablett + Sensor für LyoCube eingeforen

- Aufreinigung 2 Anneke Ende der Woche

**Comment by LauraGrabowski** [comment]
@AnnekeStrumpel Bitte die Issues mit ein paar abschließenden Infos/Kommentaren schließen ("Close this issue"), wenn es erledigt ist. Danke!

**Comment by AnnekeStrumpel** [comment]
![image](https://user-images.githubusercontent.com/89061807/152160309-7820a08b-f1be-4f30-8035-bd5bb2e33294.png)
Aufreinigung ApPDC E469Q am 09.09.21 aus Kultivierungskolben 2, 17.1% Zielenzymgehalt in der Entsalzungsfraktion (Konz.: 0.81 mg/mL)

![image](https://user-images.githubusercontent.com/89061807/152160421-a9891d05-4c0b-4421-94b3-79a14b5a1e65.png)
Aufreinigung ApPDC E469Q am 09.09.21 aus Zellpellet vom März 2021, 24.6% Zielenzymgehalt in der Entsalzungsfraktion (Konz.: 1 mg/mL)

**Comment by AnnekeStrumpel** [comment]
Rohzellextrakt:
