### ISSUE TITLE
Vorversuche ApPDC-EziG Immobilisierung

### ISSUE THREAD

**Issue by LauraGrabowski** [LauraGrabowski/student-project#5]
- mit älterem altem aufgreinigtem Enzymstock?
- Immobilisierungseffizienz der 3 EziG (Opal, Amber, Coral)
- das Beste wird ebenfalls mit Rohextrakt getestet:
  -- Proteinbestimmung Bradford/BCA-Assay

**Comment by LauraGrabowski** [comment]
1. Bindungsversuche mit EziG Opal, Amber, Coral: Bestimmung über Bradford (Proben Überstand vor und nach Inkubation mit Beads)
2. Bindungsversuche mit EziG Opal, Amber, Coral: Bestimmung über BCA-Assay (Assay mit beladenen Beads)
--> Vergleich Proteinbestimmungs-Methoden und Aussage über Immobilisierungseffizienz
3. Aktivitätstest mit bester Variante
4. Test von Rohextrakt mit bester Variante (BCA): Immobilierungseffizienz und Aktivität

**Comment by AnnekeStrumpel** [comment]
Die Immobilisierunsgversuche ergaben, dass die ApPDC am besten an die Opal Beads bindet (0,04 - 0,07 mg Enzym/mg Beads).
An die Coral Beads binden circa 0,03 mg/mg (nach Abzug der Kontrolle, da diese sich im BCA-Assay lila gefärbt hatte) und an die Amber Beads binden circa 0,02 -0,03 mg/mg

Die Immobilisierung mit dem CCE-Lyophilisat  hat gut funktioniert (wird nur noch so gemacht)

Nur noch BCA als Proteibestimmungsmethode, da Bradford für den CCE nicht geeignet ist und eine sehr geringe Beladung angibt.
