### ISSUE TITLE
Lyophilisierung und Aktivitätsbestimmung

### ISSUE THREAD

**Issue by LauraGrabowski** [LauraGrabowski/student-project#6]
- Aufgereinigte ApPDC E469Q
- Rohzellextrakt ApPDC E469Q

Routine im Umgang mit HPLC (Messung 3-OH-BA und 3-OH-PAC auf HPLC 6 oder HPLC 10)

**Comment by AnnekeStrumpel** [comment]
![image](https://user-images.githubusercontent.com/89061807/152161804-46e5e25c-40e3-4a25-8c2e-42d7c42fe88f.png)
Ergebnisse des HPLC basierten Aktivitätstest von drei ApPDCs aus verschiedenen Kultivierungen. 
Aktivität ApPDC aus Kolben 2: 0.4987 U/mL 
Aktivität ApPDC aus dem Pellet von März 2021: 0.4031 U/mL
Aktivität ApPDC aus Lyophilisat von März 2021: 0.1557 U/mL
Aktivität ApPDC Crude Cell Extract aus Kolben 2: 0.4491 U/mL
