### ISSUE TITLE
Kultivierung **Cv2025** + SDS-PAGE

### ISSUE THREAD

**Issue by LauraGrabowski** [LauraGrabowski/student-project#7]
Trafo Cv2025 + HisTag: MP15.7.b (Kanamycin), 
Vorkultur LB 
Hauptkultur 4 x 1 L AI Medium, Kolben mit den gleichen Schikanen, 37°C 2 h --> 20°C 48 h (Schüttler reserviert 4.-8.10) --> Animpfvolumen mit Ilona abklären
Pellet pro Kolben wiegen und einfrieren
Proben für SDS-Gel (5 mL, siehe SOP); Montag Gel laufen

**Comment by AnnekeStrumpel** [comment]
Kultivierung war erfolgreich und die Aufreinigung hat funktioniert (durchgeführt am 19.01.2022) 
Beim SDS-Gel ist eine zweite Band  ungefähr auf Höhe der 130 kDA Markierung zu sehen.
Nach der Entsalzung waren 120 mL mit einer Konzentration von 3.22 mg/mL vorhanden. Wurde für das Lyophilisieren 1:3 verdünnt. 
Die Zielenzymkonz. in der Entsalzungsfraktion lag bei 33 %.
