### ISSUE TITLE
Kalibrierung HPLC für Transaminase Assay (L102)

### ISSUE THREAD

**Issue by LauraGrabowski** [LauraGrabowski/student-project#9]
- Assay für Transaminase-Aktivität (Pyruvat + alpha-MBA --> Alanin + Acetophenon) mit ganzen, lyophilisierten Zellen (da nicht photometrisch messbar)

**Comment by LauraGrabowski** [comment]
@AnnekeStrumpel: Externe Kalibriergeraden erstellen bzw. mit Hilfe von Douglas/Edu Kalibrierung in Software hinterlegen. Die Konzentrationen der Proben werden dann direkt in der Software ausgerechnet.

Wichtig für spätere Immobilisierungsversuche mit Cv2025, wenn photometrische Messung nicht möglich:
- Zunächst checken, ob EziG-TA auch in Photometer messbar (in Küvette mit Rührfisch) 
- Initiale Rate von EziG-TA im Vergleich zu freier Transaminase wichtiger Indikator für mögliche Konti-ISPR Versuche

**Comment by AnnekeStrumpel** [comment]
Ist erledigt, die Kalibrierung ist in meinem Praktikumsbericht zu sehen, ich schicke Dir die Excel-Datei aber auch gerne noch einmal zu :)

**Comment by AnnekeStrumpel** [comment]
Im Phototmeter ist die Aktivität von der immobilisierter TA nicht gut zu messen, da hier sehr starke Schwankungen auftreten 
![image](https://user-images.githubusercontent.com/89061807/152158957-43721dfb-c292-4d92-98d6-6257ae4cb51b.png)

**Comment by AnnekeStrumpel** [comment]
Initiale Rate versuche ich über die HPLC Methode zu bestimmen. Ich hänge Dir hier schon mal an, was ich habe: 
![image](https://user-images.githubusercontent.com/89061807/152159431-c244665c-a05b-42e5-b4ce-97ca75b067c7.png)
